import { CalculatorApp } from './CalculatorApp.jsx';
import { ComputerApp } from './ComputerApp.jsx';
import { FileExplorerApp } from './FileExplorerApp.jsx';
import { ImageViewerApp } from './ImageViewerApp.jsx';
import { NotepadApp } from './NotepadApp.jsx';
import { PaintApp } from './PaintApp.jsx';
import { PropertiesApp } from './PropertiesApp.jsx';
import { RosoMazeApp } from './RosoMazeApp.jsx';
import { SettingsApp } from './SettingsApp.jsx';
import { TerminalApp } from './TerminalApp.jsx';
import { DoomApp } from './DoomApp.jsx';

export const appRegistry = [
  {
    id: 'explorer',
    title: 'File Explorer',
    description: 'Persistent folders and files.',
    iconTone: 'explorer',
    component: FileExplorerApp,
    defaultPosition: { x: 176, y: 92 },
    defaultSize: { width: 720, height: 460 },
    minSize: { width: 460, height: 300 },
    quickLaunch: true,
    desktop: true,
    multiInstance: true,
  },
  {
    id: 'computer',
    title: 'My Computer',
    description: 'Drives, system locations, and main shortcuts.',
    iconTone: 'computer',
    component: ComputerApp,
    defaultPosition: { x: 154, y: 86 },
    defaultSize: { width: 640, height: 420 },
    minSize: { width: 360, height: 260 },
    quickLaunch: true,
    desktop: true,
    multiInstance: false,
  },
  {
    id: 'notepad',
    title: 'Notepad',
    description: 'Simple text editor with local saving.',
    iconTone: 'notepad',
    component: NotepadApp,
    defaultPosition: { x: 238, y: 132 },
    defaultSize: { width: 560, height: 390 },
    minSize: { width: 340, height: 250 },
    quickLaunch: true,
    desktop: true,
    multiInstance: true,
  },
  {
    id: 'terminal',
    title: 'Terminal',
    description: 'Fake console with local commands.',
    iconTone: 'terminal',
    component: TerminalApp,
    defaultPosition: { x: 292, y: 154 },
    defaultSize: { width: 600, height: 360 },
    minSize: { width: 360, height: 240 },
    quickLaunch: true,
    desktop: true,
    multiInstance: true,
  },
  {
    id: 'calculator',
    title: 'Calculator',
    description: 'Basic XP-style calculator.',
    iconTone: 'calculator',
    component: CalculatorApp,
    defaultPosition: { x: 334, y: 126 },
    defaultSize: { width: 270, height: 350 },
    minSize: { width: 236, height: 318 },
    quickLaunch: false,
    desktop: true,
    multiInstance: false,
  },
  {
    id: 'paint',
    title: 'Paint',
    description: 'Simple drawing with basic tools.',
    iconTone: 'paint',
    component: PaintApp,
    defaultPosition: { x: 250, y: 94 },
    defaultSize: { width: 680, height: 500 },
    minSize: { width: 420, height: 320 },
    quickLaunch: false,
    desktop: true,
    multiInstance: true,
  },
  {
    id: 'roso-maze',
    title: 'Pac-Man',
    description: 'The classic Pac-Man arcade game in Roso OS.',
    iconTone: 'game',
    component: RosoMazeApp,
    defaultPosition: { x: 278, y: 104 },
    defaultSize: { width: 600, height: 470 },
    minSize: { width: 380, height: 330 },
    quickLaunch: false,
    desktop: true,
    multiInstance: false,
  },
  {
    id: 'doom',
    title: 'DOOM',
    description: 'The classic 1993 first-person shooter.',
    iconTone: 'doom',
    component: DoomApp,
    defaultPosition: { x: 200, y: 80 },
    defaultSize: { width: 640, height: 460 },
    minSize: { width: 320, height: 240 },
    quickLaunch: false,
    desktop: true,
    multiInstance: false,
  },
  {
    id: 'image-viewer',
    title: 'Image Viewer',
    description: 'Opens PNG images saved in Roso OS.',
    iconTone: 'image',
    component: ImageViewerApp,
    defaultPosition: { x: 286, y: 108 },
    defaultSize: { width: 560, height: 420 },
    minSize: { width: 340, height: 260 },
    quickLaunch: false,
    desktop: false,
    hidden: true,
    multiInstance: false,
  },
  {
    id: 'settings',
    title: 'Control Panel',
    description: 'Wallpapers, sound, and visual settings.',
    iconTone: 'settings',
    component: SettingsApp,
    defaultPosition: { x: 214, y: 112 },
    defaultSize: { width: 560, height: 390 },
    minSize: { width: 360, height: 270 },
    quickLaunch: false,
    desktop: true,
    multiInstance: false,
  },
  {
    id: 'properties',
    title: 'Properties',
    description: 'Details for the selected item.',
    iconTone: 'settings',
    component: PropertiesApp,
    defaultPosition: { x: 320, y: 156 },
    defaultSize: { width: 390, height: 300 },
    minSize: { width: 320, height: 240 },
    quickLaunch: false,
    desktop: false,
    hidden: true,
    multiInstance: false,
  },
];

export const getAppById = (appId) => appRegistry.find((app) => app.id === appId);

export const getQuickLaunchApps = () => appRegistry.filter((app) => app.quickLaunch);

export const getDesktopApps = () => appRegistry.filter((app) => app.desktop);
